[package]
name = "mizumi-vector-db"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
readability = "0.3.0"
tokio = { version = "1", features = ["full"] }


